# create a secrets.yaml file with the following content

apiVersion: v1
kind: ConfigMap
metadata:
  name: asmr-config
  namespace: default
data:
  MONGODB_URI: ....
  KAFKA_BROKER: ....
  KAFKA_USERNAME: ....
  KAFKA_PASSWORD: ....
  REDIS_ADDR: ....
  MONGO_URI: ....
  HOST: "rest-server"
  PROMETHEUS_HOST: "prometheus-kube-prometheus-prometheus.default"
  NEXT_PUBLIC_BACKEND_URL: "http://rest-server:8000"
  AUTH_SECRET: asmr
  AUTH_TRUST_HOST: "true"