apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: docker.io/ankush003/asmr-simulator:latest
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: MONGODB_URI
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: KAFKA_BROKER
            - name: KAFKA_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: KAFKA_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: KAFKA_PASSWORD
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: REDIS_ADDR
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: asmr-config
                  key: MONGO_URI